name: CI - Vérification HTML

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]



jobs:
  test-html:
    run-on: ubuntu-latest
    steps:
      -name: Récupération du code
       uses: action/checkout@v3


      -name: Vérifiaction syntaxe HTML
       uses: Cyb3r-Jak3/html5validator-action@v7.2.0
       with:
          root: .

